
services:
  axis-db:
    image: mongo
    ports:
      - 27017:27017
    container_name: axis-db-react
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nath
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    networks:
      - axis-networks
    volumes:
      - axis_volumes:/data/db

networks:
  axis-networks:

volumes:
  mongo-volumes:
  axis_volumes: