version: '3'

services:

  axis:
    image: axis
    ports:
      -"3000:3000"
    networks:
      - axis-networks
    container_name: axis-react
    restart: always
    depends_on:
      - axis-db
  axis-db:
    image: mongo
    ports:
      -"27017:27017"
    container_name: axis-db-react
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nath
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    networks:
      - axis-networks
    volumes:
      -axis-volumes:/data/db

networks:
  axis-networks:

volumes:
  mongo-volumes:
